### ISSUE TITLE
BOM mismatch

### ISSUE THREAD

**Issue by wannessels** [carrotIndustries/pluto#9]
Q1 is missing in bom_mouser.txt . Something like [771-BC846BW-T/R](http://www.mouser.be/ProductDetail/NXP-Semiconductors/BC846BW115/?qs=sGAEpiMZZMvplms98TlKY2Zo6yIIJX31FPTHu2sSwD0%3d)?
LED1 is missing in f-91w.bom
C2 & C3 are 22pF in f-91w.bom, but 12pF in bom_mouser.txt

Can you recommend an inductor? I'd rather get a new one instead of the one from the stock f91w board.

**Comment by wannessels** [comment]
Oh, and C2 & C3 are 22pF in f-91w.bom, but 12pF in bom_mouser.txt

**Comment by carrotIndustries** [comment]
Uh, Q1 is in the bom: https://github.com/carrotIndustries/pluto/blob/master/bom_mouser.txt#L10 looks like it's obsolete, the one you mentioned looks fine. The exact type isn't that critical, it should have a Vce max of approx 60V and the right package.

Btw, feel free to experiment with the LED, with the one in the BOM the backlight isn't very uniform. 

The load capacitors for the crystal should be 12pf as per the crystal's datasheet.

I've been looking for an inductor but haven't been able to find a replacement (10mH) that comes close. To make things harder, there's a cavity in the frame that is shaped to accommodate the stock inductor. Since you need to transplant the spring for contacting the piezo buzzer anyhow, transplanting the inductor as well didn't seem a hassle too big.

**Comment by wannessels** [comment]
Ah, I copy pasted the BOM and when I didn't get the transistor I wrongfully assumed it was not in the bom. I probably ignored a warning from mouser when importing the txt.

The original watch already has lousy backlight (more like sidelight actually), so I don't think this can be fixed, but I will try a few different leds.

**Comment by zigastegu** [comment]
@wannessels  hi, did you make your own? kind regards
update: i see you have http://www.eevblog.com/forum/oshw/diy-watch-based-on-the-casio-f-91w/msg1101051/#msg1101051
